version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_PORT=3306
    volumes:
      - .:/usr/src/app
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=desafio
    ports:
      - "3306:3306"
    expose:
      - 3306
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
